obj-y += set_scheduler.o
obj-y += chronos_seg.o
obj-y += chronos_mutex.o
obj-y += chronos_proc.o
ifeq ($(CONFIG_CHRONOS),y)
obj-m += fifo_ra.o
obj-m += rma.o
obj-m += edf.o
obj-m += hvdf.o
obj-m += lbesa.o
obj-m += dasa_nd.o
obj-m += dasa.o
obj-m += gfifo.o
obj-m += grma.o
obj-m += gedf.o
obj-m += gnp_edf.o
obj-m += ghvdf.o
obj-m += gnp_hvdf.o
obj-m += gmua.o
obj-m += ggua.o
obj-m += nggua.o
obj-m += abort_shmem.o
endif
